services:
  postgres:
    container_name: postgres-budget
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5433:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - spring-budget
    restart: unless-stopped
  backend:
    container_name: spring-budget
    build: budget-api/.
    depends_on:
      - postgres
    ports:
      - '8081:8081'
    environment:
      - jwt_secret_key=${JWT_SECRET_KEY}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/budget_tracker
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - spring-budget
    restart: unless-stopped

  frontend:
    container_name: angular-budget
    build: ./budget-ui
    depends_on:
      - backend
    ports:
      - '80:80'
    networks:
      - spring-budget

networks:
  spring-budget:
    driver: bridge
    
volumes:
  postgres:
    name: postgres-data
    driver: local
    #driver_opts:
    #  type: none
    #  o: bind
    #  device:
